As mcalling java
genevaers/Research-And-Development pull request #34
Opened 2023-09-21 04:38 UTC by neilbeesley

This is a performance improvement, by removing a lot of getmains/freemains and also using stack (CEEDSA) storage and staying in 64 bit mode whenever possible, which is the AMODE of Java.
Spellings also corrected and dead code removed.

2023-09-27 17:38 UTC, KipTwitchell commented on POC-iterations/ASMcallingJAVA/ASM/asminf264.s
> +MYDSA    CEEDSA SECTYPE=XPLINK         Dynamic Save Area
THEDSA    CEEDSA SECTYPE=XPLINK         Dynamic Save Area

2023-09-27 17:40 UTC, KipTwitchell commented on POC-iterations/ASMcallingJAVA/ASM/asminf264.s
> +         LAY   R13,MYWORK-MYDSA(,R4)
LAY   R13,MYWORK-THEDSA(,R4)

2023-09-27 17:42 UTC, KipTwitchell commented on POC-iterations/ASMcallingJAVA/ASM/gvbjmain.s
> +OUTDCB   DS    A
add comment that it is the address of the DCB

2023-09-27 17:45 UTC, KipTwitchell commented on POC-iterations/ASMcallingJAVA/ASM/gvbjmain.s
>  PAADDR2  DS    D
Add comments about each parameter

2023-09-27 18:18 UTC, KipTwitchell commented on POC-iterations/ASMcallingJAVA/ASM/gvbjmr95.s
> +MAIN_114 EQU   *                  LOAD AND EXECUTE GVBMR95 OR SOMETHING
add more prominent comment on this.

2023-09-27 18:21 UTC, KipTwitchell commented on POC-iterations/ASMcallingJAVA/ASM/gvbjmr95.s
>           STIMER WAIT,BINTVL=FIVESEC
add comment about subprograms cleaning up.

2023-09-27 18:24 UTC, KipTwitchell commented on POC-iterations/ASMcallingJAVA/ASM/gvbjpost.s
>  PAADDR2  DS    D
Comments

2023-09-27 18:29 UTC, KipTwitchell commented on POC-iterations/ASMcallingJAVA/ASM/gvbjwait.s
>  PAADDR2  DS    D
comments

2023-09-27 18:34 UTC, KipTwitchell requested changes
See comments.

2023-09-28 22:39 UTC, neilbeesley commented
Changes made.

2023-09-29 18:11 UTC, KipTwitchell commented on POC-iterations/ASMcallingJAVA/ASM/gvbjmain.s
>  MAIN_096 EQU   *
no change needed.

2023-09-29 18:15 UTC, KipTwitchell approved these changes

2023-09-29 18:16 UTC, merged